### ISSUE TITLE
关于Taro集成WxComment组件遇到的问题

### ISSUE THREAD

**Issue by FatDoge** [yicm/WxComment#18]
**问题描述**
想在Taro应用中集成小程序的评论组件但是编译出错。大佬感兴趣可以集成看看[Taro相应文档](https://nervjs.github.io/taro/docs/mini-third-party.html)
**复现步骤**
1、将WxComment下载到本地并放在了Taro项目的src目录下
2、填写好了LeanCloud对应的appid和appkey
3、在Taro项目中相应page中进行引用，配置config信息（完全按文档来的）
4、编译失败
```
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'bind' of undefined 
 TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:1319:47)
    at e (http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:11:96)
    at Object.<anonymous> (http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:1361:98)
    at e (http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:11:96)
    at http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:22:18
    at http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:23:4
    at http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:7:179
    at http://127.0.0.1:53367/appservice/WxComment/libs/leancloud/av-weapp-min.js:8:2
    at require (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1077084)
    at http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1076694
console.error @ VM14103:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559204598019:1522
window.onerror @ VM14103:1
scriptLoaded @ appservice?t=1559204598019:1607
script.onload @ appservice?t=1559204598019:1619
error (async)
239 @ VM14103:1
t @ VM14103:1
237 @ VM14103:1
t @ VM14103:1
(anonymous) @ VM14103:1
(anonymous) @ VM14103:1
VM14334:4 Thu May 30 2019 16:23:23 GMT+0800 (中国标准时间) sitemap 索引情况提示
VM14103:1  根据 sitemap 的规则[0]，当前页面 [pages/answer/answer?lessonId=1] 将被索引
console.warn @ VM14103:1
(anonymous) @ VM14334:6
(anonymous) @ VM14334:13
VM14103:1 jsEnginScriptError
Component is not found in path "WxComment/component/WxComment/WxComment" (using by "pages/answer/answer");onAppRoute
Error: Component is not found in path "WxComment/component/WxComment/WxComment" (using by "pages/answer/answer")
    at m (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:944277)
    at m (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:944463)
    at http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:961690
    at Object.t.addView (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:962236)
    at Function.value (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1041611)
    at kt (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1055700)
    at http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1059176
    at Tt (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1059239)
    at Function.<anonymous> (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1062461)
    at i.<anonymous> (http://127.0.0.1:53367/appservice/__dev__/WAService.js:1:1034791)
console.error @ VM14103:1
errorReport @ WAService.js:1
(anonymous) @ WAService.js:1
x @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1559204598019:1522
(anonymous) @ appservice?t=1559204598019:1522
(anonymous) @ appservice?t=1559204598019:1522
(anonymous) @ appservice?t=1559204598019:1522
a.onmessage @ appservice?t=1559204598019:1522
```

**Comment by yicm** [comment]
@FatDoge 你路径是不是配置对了

**Comment by FatDoge** [comment]
今天再次尝试后，还是遇到了问题。

> 需要集成WxComment的组件

`config = {
      navigationBarTitleText: '课程',
      // // 定义需要引入的第三方组件
      usingComponents: {
        'wx-comment': '../../WxComment/component/WxComment/WxComment.js' // 书写第三方组件的相对路径
      }
    }`
路径没有错误，但是编译会报错，报错如下：
./pages/answer/answer.wxml
 unexpected tag, near `wx-comm...`
  17 |         </view>
  18 |         <view>
> 19 |             <wx-comment submitBtnText="回复" articleID="1" contentLen="1"></wx-comment>
     |             ^
  20 |         </view>
  21 |         <view class="answer-footer flex-wrp">
  22 |             <view class="operation-wrp flex-item">

**Comment by FatDoge** [comment]
对了，这个需不需要配置es6转es5的，开发者工具报了cannot read property 'bind' of undefined的错误

**Comment by yicm** [comment]
@FatDoge 可能吧，leancloud js库是用的es6

**Comment by hufans** [comment]
> 对了，这个需不需要配置es6转es5的，开发者工具报了cannot read property 'bind' of undefined的错误

请问最后那个问题怎么解决的？

**Comment by FatDoge** [comment]
@hufans  将打包后的文件全部删除，重新编译。
